### ISSUE TITLE
Color in menu on windows

### ISSUE THREAD

**Issue by OnePunchMan007** [TimGr/valley-vscode#1]
🚧 Please check first if you are using the latest version of Valley.

**Expected behavior/design**
See the menu

**Screenshots**
![bug-Valley](https://user-images.githubusercontent.com/48897243/75983791-291cc980-5eb7-11ea-9062-75ee8034273c.png)

**Setup (please complete the following information):**
 - OS: windows 10
 - Visual Studio Code Version [1.42.1]

**Comment by lucastrvsn** [comment]
On arch linux as well.

![Screenshot from 2020-03-05 10-45-20](https://user-images.githubusercontent.com/8826449/75987309-7bb5b000-5ece-11ea-9116-78ea1dbe6843.png)

**Comment by timnarr** [comment]
Hey @OnePunchMan007, @lucastrvsn  

thanks for opening this issue and your screenshots. Please be so kind and update Valley. This should look nice in the latest version. 

If something is still not right, please feel free to re-open the issue.
Thank you
