### ISSUE TITLE
Nice and Clean

### ISSUE THREAD

**Issue by mikeerickson** [TimGr/valley-vscode#2]
I currently use Material Theme (Panelnight) and your theme is quite appealing.

Would you mind supply a screenshot when integrated terminal is displayed, as well as from code inspection?  As far as inspection is concerned, it is quite "crowded and confusing" using Material

**Comment by timnarr** [comment]
Hi @mikeerickson 

thank you for opening this issue.

Here is a screenshot of the terminal. I have planned some minor adjustments of the colors. So the colors might change. But nothing big:
<img width="1080" alt="valley-terminal-colors" src="https://user-images.githubusercontent.com/3532570/76247469-e3a62680-623f-11ea-845b-86b16a50bd01.png">

Can you describe in more detail what you expect/would like to see for "Code Inspection"? I'm not sure which vs code feature you mean exactly and what I can show you? Perhaps you also have a suitable code example?

Thank you

**Comment by mikeerickson** [comment]
I am referring to quick peek window (sorry, I was a bit vague on the inspection statement). Basically all the tools that “peek” at code. 

I can send you a screenshot later this evening when I return to computer.

**Comment by timnarr** [comment]
Hey @mikeerickson 

I have added more screenshots that show different peek views. Please have a look:
https://github.com/TimGr/valley-vscode/blob/master/screenshots.md

I'd close this issue for now, but feel free to re-open it if you notice something is out of place.
Thank you
