### ISSUE TITLE
Support for italic font ?

### ISSUE THREAD

**Issue by Epistol** [TimGr/valley-vscode#3]
As a user of Dank Mono (and Fira Code sometimes), not having a compatible theme for italic is a no-go but the theme has potential so could be a nice feature.

**Comment by timnarr** [comment]
Hi @Epistol, 
thank you for opening this issue. 
I am currently looking for a nice solution how a user can easily enable or disable italics. 

From your point of view, what should be displayed as italic? Variables, function parameters, attribute-names? What else?

**Comment by Epistol** [comment]
Found this : https://dev.to/salted-bytes/adding-italics-support-to-your-favourite-vscode-theme-2ec9 

Apparently this bit of code works nice : 

`{
  "scope": "emphasis",
  "settings": {
    "fontStyle": "italic"
  }
},`

**Comment by timnarr** [comment]
Hi @Epistol ,
with the latest update to version 0.2.0 I have introduced an "italic" variant. Probably some "italics" are still missing, but that will come step by step. :)
