### ISSUE TITLE
iTerm Port

### ISSUE THREAD

**Issue by francisceril** [TimGr/valley-vscode#4]
Would love to have the color scheme on iTerm. Can you port it please. 😃

**Comment by timnarr** [comment]
hi @francisceril  
already working on it 😎 I hope I can publish it soon. I'll let you know.

**Comment by timnarr** [comment]
Hi @francisceril 
please have a look here:
https://github.com/TimGr/valley-iterm

Let me know what you think :-)

**Comment by francisceril** [comment]
It

> Hi @francisceril
> please have a look here:
> https://github.com/TimGr/valley-iterm
> 
> Let me know what you think :-)

It is awesome. Thanks for the work!
