### ISSUE TITLE
Question: How to have dedicated color for an object's key

### ISSUE THREAD

**Issue by jonyeezs** [TimGr/valley-vscode#5]
I want to `tokenColorCustomizations` the keys of an object to a different color.

Can't seem to get it to work. What can i do?

I got this

```json
"editor.tokenColorCustomizations": {
    "[Valley]": {
      "textMateRules": [
         {
          "name": "Object property",
          "scope": [
            "meta.object-literal.key",
            "meta.object-literal.key.ts",
            "meta.object-literal.key.js"
          ],
          "settings": {
            "foreground": "#9ab3b9",
          }
        },
      ]
   }
}
```

**Comment by timnarr** [comment]
Hi @jonyeezs 

I just tried it and your color rules works fine for me (testet in .js and .jsx files).
![color-rules-valley](https://user-images.githubusercontent.com/3532570/93903277-be1ecd00-fcf8-11ea-841b-3881e0b9f728.png)

Does it work if you disable all other extensions except Valley?

**Comment by jonyeezs** [comment]
Thanks for replying!

I've disabled all extensions and only enabled Valley.

I see that the colors do get applied **BUT** (and this is where it gets weird) it falls back to another settings
![image](https://user-images.githubusercontent.com/10862726/93945480-56a96180-fd7a-11ea-8d91-686f0d6db96e.png)

I also notice the color changes after `ts/js  language feature` has finish loading

**Comment by timnarr** [comment]
Hi @jonyeezs 

ah, now I understand. It seems you are using semantic syntax highlighting which is causing this weird switch when the language feature finished loading.

I think you have two options now:
1.) Deactivate semantic highlighting in your settings via `"editor.semanticHighlighting.enabled": false` and apply your customizations like you wrote in your first comment.
2.) If you want semantic highlighting enabled you can overwrite the styles like this
```
"editor.semanticTokenColorCustomizations": {
    "[Valley]": {
        "rules": {
            "property.declaration": {
                "foreground": "#9ab3b9"
            }
        }
    } 
}
```
If you have a look at your last screenshot you can find these two rules I've used (`property.declaration`) under "semantic token type" and "modifiers"

Hope this helps :) 
You can read more about semantic highlighting here https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

**Comment by jonyeezs** [comment]
Went with opt 2, that worked superbly! You're a genius!
